var mongoose =require("mongoose");
var hvacSchema=new mongoose.Schema({
	regiao:String,
	jobcard_cod:String,
	regiao_ref:String,
	departamento:String,
	departamento_ref:String,
	tecnico:String,
	tecnico_ref:String,
	cliente:String,
	jobcard_sitearrivaltime:String,
	cliente_ref:String,
	jobcard_holdaction:String,
	jobcard_holdreason:String,
	jobcard_tecnicoid:String,
	jobcard_callcentercomments:[String],
	local:String,
	jobcard_departamentoid:String,
	jobcard_traveldistance:String,
	jobcard_planneddatems:Number,
	jobcard_traveldurationms:String,
	jobcard_arrivaldepartureduration:String,
	jobcard_planneddate:String,
	jobcard_tecarrivalduration:String,
	jobcard_estimadadatachegadams:Number,
	jobcard_estimadadatachegada:String,
	jobcard_estimahorachegada:String,
	jobcard_departamento:String,
	jobcard_jobtype:String,
	jobcard_loggedby:String,
	jobcard_responsedays:Number,
	sparesArrayJobcard:[{jobcard_itemid:String,jobcard_item:String,jobcard_quantityuse:Number, jobcard_itemphoto:String, jobcard_datauso:String, jobcard_itemserialized:String, jobcard_itemnrserie:String, jobcard_itemreplace:String, jobcard_itemreplacereason:String, jobcard_nomeitemreplace:String, jobcard_itemreplacephoto:String, jobcard_itemowner:String}],
	jobcard_regiao:String,
	jobcard_jobinfo:[String],
	equipamentoArrayJobcard:[{jobcard_equiptype:String, jobcard_manufacturer:String, jobcard_model:String, jobcard_serialnumber:String, jobcard_capacity:String, jobcard_type:String}],
	jobcard_controladorintervenientes:[String],
	jobcard_controlador:[Number],
	jobcard_ttnumber:Number,
	ttnumber_status:String,
	jobcardphotoinfo:[String],
	jobcard_prioritycomments:[{jobcard_commentname:String, jobcard_comment:String, jobcard_commentpriority:String}],
	jobcard_callcenteractions:[{jobcard_callcenteractionname:String, jobcard_callcenteraction:String, jobcard_callcenteractionreason:String}],
	jobcard_tecarrivaltime:String,
	jobcard_sitearrivaldate:String,
	jobcard_tecarrivaldate:String,
	geolocationJobcardInfo:[{jobcard_latitude:String, jobcard_longitude:String}],
	jobcard_sitedeparturedate:String,
	jobcard_site:String,
	jobcard_siteid:String,
	jobcard_priority:String,
	jobcard_clientenome:String,
	jobcard_clienteid:String,
	jobcard_tecniconome:String,
	jobcard_tecnicoid:String,
	jobcard_audittrail:[{jobcard_audittrailname:String, jobcard_audittrailaction:String, jobcard_audittraildate:String}],
	jobcard_estadoactual:String, 
	jobcard_call:[String],
	data_registojobcard:{type:Date, 'default':Date.now},
	provincia:String,
	provincia_ref:String,
	tipo_trabalho:String,
	tecnico:String,
	tecnico_ref:String,
	razao:String,
	jobcard_wait:String,
	prioridade:String,
	filial:String,
	jobcard_sitedeparturetime:String,
	jobcard_workstatus:String,
	jobcard_hsreason:String,
	filial_ref:String,
	geolocalizacao:[{
	latitude:String,
	jobcard_linemanagercell:String,
	longitude:String}],
	jobcard_linemanagerid:String,
	data_criacao:{
		type:Date,
		"default":Date.now
	},
	data_ultimaactualizacaojobcard:{
		type:Date,
		"default":Date.now
	},
	generatorArrayJobcard:[{jobcard_generatorname:String, jobcard_generator:String, jobcard_generatormobilefixed:String,jobcard_previousgeneratorhrs:String,jobcard_currentgeneratorhours:String, jobcard_previousrefuelhrs:String,jobcard_generatorrefuel:String,jobcard_litersoil:String, jobcard_dsc:String,jobcard_refuelreason:String,jobcard_generatorbeenserviced:String, jobcard_priceperliter:String}],
	criado_por:String,
	prioridade:String,
	jobcard_credelecinfo:[{jobcard_currentkwh:String, jobcard_kwhafter:String, jobcard_amountadded:String, jobcard_transactionr:String, jobcard_credelecnr:String}],
	data_inicio:String,
	data_finalizacao:String,
	viatura:String,
	jobcard_analisederisco:{jobcard_risk1:String, jobcard_risk2:String, jobcard_risk3:String, jobcard_risk4:String, jobcard_risk5:String, jobcard_risk6:String, jobcard_risk7:String, jobcard_risk8:String, jobcard_risk9:String, jobcard_risk10:String, jobcard_risk11:String, jobcard_risk12:String, jobcard_risk13:String, jobcard_risk14:String, jobcard_risk15:String, jobcard_risk16:String, jobcard_risk17:String, jobcard_risk18:String, jobcard_risk19:String, jobcard_radiocomments:String},
	jobcard_analisederiscoAmbiental:{jobcard_risk21:String, jobcard_risk22:String, jobcard_risk23:String, jobcard_risk24:String, jobcard_risk25:String, jobcard_risk26:String, jobcard_risk27:String, jobcard_risk28:String, jobcard_radiocomments2:String},
	status:String,
	assistentes:[{nome:String, referencia:String}],
	razaoreprovar:String,
	photoinfo:[String],
	controlador:[Number],
	pessoacontacto_nome:String,
    pessoacontacto_numero:String,


	audit_trail:[{
		nome_ref:String,
		nome:String,
		data:Date,
		acao:String
	}],
	

	travel_info:[{
		distancia_prevista:String,
		duracao_viagem:String,

	}],
	origem:{latitude:String,
	longitude:String},

	//Campos Padrão
    data_registojobcardms:Number,
    datareporte:String,
	horareporte:String,
    restorationhrs:Number,
    workstatus:String,
	remedialaction:String,
	healthsafety:String,
	hsreason:String,
    tecarrivaldate:String,
	tecarrivaltime:String,
	sitearrivaldate:String,//maintenancedate
	sitearrivaltime:String,
	tecarrivalduration:String,
	sitedeparturedate:String,
	sitedeparturetime:String,
	arrivaldepartureduration:String,
	traveldistance:String,
	travelduration:String,
	traveldurationms:Number,
	estimadadatachegadams:Number,
	estimadadatachegada:String,
	estimahorachegada:String,


	// Futuros campos
	trabalho_feito:[String],
	responsedays:Number,
    wait:String,
	estadoactual:String,
    ttnumber:Number,
    assinatura:String,

	auditoria:[{
		nome:String,
		ref:String,
		data:Date,
		acao:String
	}],

	spares_usados:[{
		descricao:String,
		quantidade:String,
		referencia:String
	}],
	
	genarator:[{
		jobcard_filtroAr:String,
		jobcard_filtroOleo:String,
		jobcard_filtrodiesel:String,
		jobcard_element:String,
		jobcard_oleo:String,
		jobcard_nivelOleo:String,
		jobcard_nivelCoolant:String,
		jobcard_nivelBaterias:String,
		jobcard_limpezaGerador:String,
		jobcard_lubrificacao:String,
		jobcard_fugas:String,
		jobcard_nivelDiesel:String,
		jobcard_ruidos:String,
		jobcard_funcionamento:String,}],

	airconds:[{
		jobcard_limpezaFiltroAr:String,
		jobcard_limpezaExternaCondensador:String,
		jobcard_limpezaExternaEvaporador:String,
		jobcard_limpezaPermutadorEvaporador:String,
		jobcard_limpezaPermutadorCondensador:String,
		jobcard_funcionamentoMotoDeflectores:String,
		jobcard_drenagemLimpezaTabuleiroCondesandores:String,
		jobcard_fugasFrigorifico:String,
		jobcard_reapertos:String,
		jobcard_estadoIsolamento:String,
		jobcard_ruidosVibracoes:String,
		jobcard_estadoFiltros:String,
		jobcard_ventladores:String,
		jobcard_acessoAr:String,}],

		reportetrabalho:[{
			coment:String,
			Problemas:String,
			Qual:String,
		}]
	})
	hvacSchema.statics.gravar_hvac=function(armaz, callback){
		this.create(armaz, callback)
	}

module.exports=mongoose.model("Climatizacao", hvacSchema, "Climatizacao");